EmpReview/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('people/', views.PersonView.as_view(), name='people'),
    path('person/<uuid:pk>', views.PersonDetail, name='person-detail'),
    path('review/<uuid:pk>', views.ReviewDetailView.as_view(), name='review-detail'),
    path('approval/<uuid:pk>', views.ApprovalDetailView.as_view(), name='approval-detail'),
    path('reviews/my_created_reviews.html', views.ReviewsByRequester.as_view(), name='my_created_reviews'),
    path('people_choice.html', views.search_person, name='people_choice'),
    path('success.html', views.success, name='success'),
    path('get_or_create/<int:id>', views.get_or_create, name='get-or-create')
    ]

# Person CRUD URLs

urlpatterns += [
    path('person/create', views.add_person, name='person-create'),
    path('person/<uuid:pk>/update/', views.PersonUpdate.as_view(), name='person-update'),
    path('person/<uuid:pk>/delete/', views.PersonDelete.as_view(), name='person-delete'),
    ]

# Review CRUD URLs

urlpatterns += [
    path('review/create/<uuid:pk>', views.add_review, name='review-create'),
    # path('review/<uuid:pk>/update/', views.ReviewUpdate.as_view(), name='review-update'),
    # path('review/<uuid:pk>/delete/', views.ReviewDelete.as_view(), name='review-delete'),
    ]

urlpatterns += [
    path('approval/create/<uuid:pk>', views.add_approval, name='approval-create'),
    # path('approval/<uuid:pk>/update/', views.ApprovalUpdate.as_view(), name='approval-update'),
    # path('approval/<uuid:pk>/delete/', views.ReviewDelete.as_view(), name='approval-delete'),
]

# urlpatterns += [
#     path('user_creation/', views.add_users_to_db, name='add-users-to-db'),
#     path('update_profiles/', views.create_or_update_profile, name='create-update-profile'),
#     ]

urlpatterns += [
    path('scratchtest/', views.scratch_test, name='scratchtest'),
    ]

EmpReview/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils import timezone as tz
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    userId = models.CharField(max_length=50, blank=True)
    managerId = models.CharField(max_length=50, blank=True)
    status = models.CharField(max_length=50)

    def name(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    class Meta:
        ordering = ('user__last_name', 'user__first_name')


class Person(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE, related_name='employee', null=True)
    mgr_name = models.ForeignKey(Employee, on_delete=models.CASCADE, default=None, help_text="Manager Name",
                                 related_name="Manager_Name", null=True)

    current_position = models.CharField(max_length=30, help_text="Current Position")
    new_position = models.CharField(max_length=30, help_text="Promotion Position")

    PATHS = (
        ('m', 'Management'),
        ('e', 'Expert'),
    )

    current_path = models.CharField(
        max_length=1,
        choices=PATHS,
        blank=True,
        default='e',
        help_text="Current Career Path")
    new_path = models.CharField(
        max_length=1,
        choices=PATHS,
        blank=True,
        default='e',
        help_text="New Career Path (choose even if the path is not changing)"
    )

    JOBS = (
        ('x', 'Executive'),
        ('m', 'Management'),
        ('s', 'Sales'),
        ('t', 'Technical'),
        ('p', 'Professional'),
        ('c', 'Client Services'),
    )

    current_job = models.CharField(
        max_length=1,
        choices=JOBS,
        blank=True,
        help_text="Current Job Category"
    )

    new_job = models.CharField(
        max_length=1,
        choices=JOBS,
        blank=True,
        help_text="New Job Category (choose even if the category is not changing)"
    )

    LEVELS = (
        ('e7', 'E7'),
        ('m6', 'M6'),
        ('m5', 'M5'),
        ('m4', 'M4'),
        ('m3', 'M3'),
        ('m2', 'M2'),
        ('sm5', 'SM5'),
        ('sm3', 'SM3'),
        ('s5', 'S5'),
        ('s4', 'S4'),
        ('s3', 'S3'),
        ('s2', 'S2'),
        ('s1', 'S1'),
        ('t5', 'T5'),
        ('t4', 'T4'),
        ('t3', 'T3'),
        ('t2', 'T2'),
        ('t1', 'T1'),
        ('p5', 'P5'),
        ('p4', 'P4'),
        ('p3', 'P3'),
        ('p2', 'P2'),
        ('p1', 'P1'),
        ('cm5', 'CSM5'),
        ('cm2', 'CSM2'),
        ('cs5', 'CS5'),
        ('cs4', 'CS4'),
        ('cs3', 'CS3'),
        ('cs2', 'CS2'),
    )

    current_level = models.CharField(
        max_length=3,
        choices=LEVELS,
        blank=True,
        help_text="Current Level")

    new_level = models.CharField(
        max_length=3,
        choices=LEVELS,
        blank=True,
        help_text="New Level")

    requester = models.CharField(
        max_length=1,
        blank=True,
        help_text="Not Used")

    class Meta:
        # ordering = ['last_name', 'first_name']
        app_label = 'EmpReview'

    def get_absolute_url(self):
        return reverse('person-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.employee.user.last_name}, {self.employee.user.first_name}'


class Review(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular review")
    person = models.ForeignKey('Person', on_delete=models.SET_NULL, null=True)
    review_date = models.DateField(default=tz.now, help_text="Date of review")
    reviewer = models.ForeignKey(Employee, on_delete=models.DO_NOTHING, null=True, related_name='reviewer',
                                 help_text="Manager writing the review")
    approver = models.ForeignKey(Employee, max_length=50,
                                 on_delete=models.DO_NOTHING, related_name='appover',
                                 help_text="Manager who will be approving")
    role_info = models.TextField(max_length=1000, help_text="Role information (please see text on the page for more"
                                                            "information).")
    person_info = models.TextField(max_length=1000, help_text="Info about the person (please see text on the page"
                                                              "for more information).")
    performance_quality = models.BooleanField(blank=True, help_text="Work Quality")
    performance_goals = models.BooleanField(blank=True, help_text="Meeting Goals")
    skills_require = models.BooleanField(blank=True, help_text="Required skills")
    skills_compare = models.BooleanField(blank=True, help_text="Skills compared to colleagues")
    values_company = models.BooleanField(blank=True, help_text="Company Values")
    values_interest = models.BooleanField(blank=True, help_text="Interest in projects")
    communication_appropriate = models.BooleanField(blank=True, help_text="Communicate appropriately?")
    communication_respect = models.BooleanField(blank=True, help_text="Communicate with respect?")
    leadership_principles = models.BooleanField(blank=True, help_text="Show leadership principles?")
    leadership_motivate = models.BooleanField(blank=True, help_text="Motivate Others?")
    feedback = models.TextField(max_length=1000, help_text="Specific feedback from others")
    ready_for_review = models.BooleanField(blank=True, default=True, help_text="Ready for manager approval")

    def get_absolute_url(self):
        return reverse('review-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.person.employee.user.last_name}; {self.review_date}'

    def meta(self):
        app_label = 'EmpReview'


class Approval(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this approval")
    review = models.OneToOneField('Review', on_delete=models.DO_NOTHING, null=True)
    person = models.ForeignKey('Person', on_delete=models.DO_NOTHING, null=True)
    approval_date = models.DateField(default=tz.now, help_text="Date of Approval")
    business_case = models.BooleanField(blank=True, help_text="Meets business requirements?")
    base_salary = models.DecimalField(max_digits=7, decimal_places=2, help_text="New Salary")

    CURRENCY = (
        ('gbp', 'British Pound'),
        ('cad', 'Canadian Dollars'),
        ('usd', 'US Dollars'),
    )

    currency_type = models.CharField(max_length=3, choices=CURRENCY, help_text="Currency Type")

    variable_comp = models.CharField(max_length=200, help_text="Variable Compensation Element?")
    budget = models.BooleanField(blank=True, help_text="Budget available?")
    equity = models.BooleanField(blank=True, help_text="Trigger Equity or LTIP?")
    next_increase = models.BooleanField(blank=True, help_text="Exclude from next increase?")
    final_approver = models.ForeignKey(Employee, on_delete=models.DO_NOTHING, help_text="Final Approver")
    approved = models.BooleanField(blank=True, help_text="Approved?")

    def get_absolute_url(self):
        return reverse('approval-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.person.employee.name}, {self.review.review_date}'


@receiver(post_save, sender=User)
def create_employee_profile(sender, instance, created, **kwargs):
    if created:
        Employee.objects.create(user=instance)
        print("Profile created for", User)


@receiver(post_save, sender=User)
def save_employee_profile(sender, instance, **kwargs):
    instance.employee.save()
    print("Profile saved")

EmpReview/forms.py
from django.forms import ModelForm, ModelChoiceField, TextInput, Select
from EmpReview.models import Person, Review, Approval, Employee
from django.utils.translation import gettext_lazy as _


class EmpSearch(ModelForm):

    class Meta:
        model = Person
        fields = ('employee',)
        widgets = {'employee': Select(attrs={'class': 'form-control'})}

class PersonForm(ModelForm):

    class Meta:
        model = Person
        fields = (
            'employee',
            'current_position',
            'new_position',
            'current_path',
            'new_path',
            'current_job',
            'new_job',
            'current_level',
            'new_level',
        )

        widgets = {
            'employee': Select(attrs={'class': 'form-control'}),
            'current_position': TextInput(attrs={'class': 'form-control'}),
            'new_position': TextInput(attrs={'class': 'form-control'}),
            'current_path': Select(attrs={'class': 'form-control'}),
            'new_path': Select(attrs={'class': 'form-control'}),
            'current_job': Select(attrs={'class': 'form-control'}),
            'new_job': Select(attrs={'class': 'form-control'}),
            'current_level': Select(attrs={'class': 'form-control'}),
            'new_level': Select(attrs={'class': 'form-control'}),
        }


class PersonEditForm(ModelForm):
    class Meta:
        model = Person
        fields = (
            'mgr_name',
            'current_position',
            'new_position',
            'current_path',
            'new_path',
            'current_job',
            'new_job',
            'current_level',
            'new_level',
        )

        widgets = {
            'current_position': TextInput(attrs={'class': 'form-control'}),
            'new_position': TextInput(attrs={'class': 'form-control'}),
            'current_path': Select(attrs={'class': 'form-control'}),
            'new_path': Select(attrs={'class': 'form-control'}),
            'current_job': Select(attrs={'class': 'form-control'}),
            'new_job': Select(attrs={'class': 'form-control'}),
            'current_level': Select(attrs={'class': 'form-control'}),
            'new_level': Select(attrs={'class': 'form-control'}),
        }


# Create Review Form
class ReviewForm(ModelForm):
    class Meta:
        model = Review
        exclude = ['id', 'person', 'review_date', 'ready_for_review']


# Approval Form
class ApprovalForm(ModelForm):
    class Meta:
        model = Approval
        exclude = ['id', 'review', 'final_approver', 'approved']

EmpReview/templates/EmpReview/approval_form.html
{% extends "base.html" %}

{% block content %}

    <h2>Approval form for {{ review_instance.person.first_name }} {{ review_instance.person.last_name }}</h2>
    <br/><br/>

    <form action="" method=POST>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Approve" class="btn btn-secondary">
    </form>

{% endblock %}

EmpReview/templates/EmpReview/my_created_reviews.html
{% extends "base.html" %}

{% block content %}

<h1>My Created Reviews</h1>

    {% if review_list %}
    <ul>
        {% for review in review_list %}
        <li>
            <a href="{{ review.get_absolute_url }}">{{ review.person }} ({{ review.review_date }})</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You have not created any reviews yet.</p>

    {% endif %}
{% endblock %}

EmpReview/templates/EmpReview/people_choice.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="text-center container">
            <br>
            <h2 class="text-center">Search for people</h2>
            <br>
            <form method="GET">
                <input type="text" name="name" placeholder="Search..." class="text-center" />
                <button type="submit" class="btn-danger btn-sm">SEARCH USERS</button>
            </form>
        </div>
        <br><br>
        <div class="row">
            {% for user in all_users %}
                <div class="col-md-4 col-sm-6 col-lg-3">
                    <div class="card">
                        <div class="card-body text-center">
                            <p class="card-text"><a href="{% url 'get-or-create' user.id %}">{{ user.name }}</a></p>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

EmpReview/templates/EmpReview/person_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Person</h1>

<p>Are you sure you want to delete the person: {{ person }}?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

EmpReview/templates/EmpReview/person_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ person.employee.user.first_name }} {{ person.employee.user.last_name }}</h1>

  <p><strong>Current Position: </strong>{{ person.get_current_position_display }}</p>
  <p><strong>Current Path: </strong>{{ person.get_current_path_display }}</p>
  <p><strong>Current Job: </strong>{{ person.get_current_job_display }}</p>
  <p><strong>Current Level: </strong>{{ person.get_current_level_display }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Reviews</h4>
    {% for review in person.review_set.all %}
      <hr>
    <p class="{% if review.ready_for_review == True %}text-warning{% else %}text-success{% endif %}">
      <strong><a href="{% url 'review-detail' review.pk %}"> {{ review.review_date }} </a></strong>
    </p>
    {% if review.ready_for_review == True %}
      <p><strong>This review is waiting for manager review</strong></p>
    {% endif %}
    <p><strong>Approver: </strong>{{ review.approver }}</p>
    {% endfor %}
    <hr>
    <br><br>

    <h3>Assessment</h3>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'review-create' person.id %}" method="post">
      {% csrf_token %}
     <table>
       {{ form.as_table }}
       {{ form.errors }}
     </table>
     <input type="submit" value="Create Review">
    </form>
  </div>
{% endblock %}

EmpReview/templates/EmpReview/person_form.html
{% extends "base.html" %}

{% block content %}
    <h3>Please complete all fields below.</h3>
    <br><br>
    <h5>{{ self.object.name }}</h5>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Next">
    </form>
{% endblock %}

EmpReview/templates/EmpReview/person_list.html
{% extends "base.html" %}

{% block content %}
    <h1>People List</h1>
    {% if people_list %}
    <ul>
        {% for person in people_list %}
            <li>
                <a href="{{ person.get_absolute_url }}">{{ person.employee.user.last_name }}, {{ person.employee.user.first_name }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are currently no people.</p>
    {% endif %}
{% endblock %}

EmpReview/templates/EmpReview/review_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ review.person.first_name }} {{ review.person.last_name }}</h1>
    <h3>Review Date: {{ review.review_date }}</h3>

    <p>Review Details:</p>
    <br>
    <p><strong>Approver: </strong>{{ review.approver }}</p>
    <p><strong>Role Information: </strong><i>(What is the business reason for this promotion?) </i>{{ review.role_info }}</p>
    <p><strong>The Person: </strong><i>(Why are you recommending this employee for promotion?) </i>{{ review.person_info }}</p>
    <h4>Performance</h4>
    <p><i>Does the employee consistently produce high quality work? </i>
        {% if review.performance_quality %}Yes
        {% else %}No{% endif %}</p>
    <p><i>Does the employee consistently exceed the goals and expectations of their role? </i>
        {% if review.performance_goals %}Yes
        {% else %}No{% endif %}</p>
    <h4>Skills & Capabilities</h4>
    <p><i>Does the employee demonstrate some of the skills and capabilities that are required at the next level? </i>
        {% if review.skills.require %}Yes
        {% else %}No{% endif %}</p>
    <p><i>Is this employee significantly more skilled than other colleagues at their level? </i>
        {% if review.skills_compare %}Yes
        {% else %}No{% endif %}</p>
    <h4>Values & Attitude</h4>
    <p><i>Does the employee model our Company values? </i>
        {% if review.values_company %}Yes
        {% else %}No{% endif %}</p>
    <p><i>Does the employee demonstrate an interest and willingness to get involved in new work / initiatives / projects etc? </i>
        {% if review.values_interest %}Yes
        {% else %}No{% endif %}</p>
    <h4>Communication</h4>
    <p><i>Does the employee communicate appropriately to colleagues and/or customers? </i>
        {% if review.communication_appropriate %}Yes
        {% else %}No{% endif %}</p>
    <p><i>Does the employee respect other people’s thoughts, views and opinions? </i>
        {% if review.communication_respect %}Yes
        {% else %}No{% endif %}</p>
    <h4>Leadership</h4>
    <p><i>Does the employee model our leadership principals? </i>
        {% if review.leadership_principles %}Yes
        {% else %}No{% endif %}</p>
    <p><i>Does the employee frequently encourage or motivate their colleagues? </i>
        {% if review.leadership_motivate %}Yes
        {% else %}No{% endif %}</p>
    <br>
    <p><strong>Feedback: </strong></p>
    <p>{{ review.feedback }}</p>
    <br>
    <button onclick='location.href="{% url 'approval-create' object.id %}"'>Approve</button>
    <button onclick="location.href='#'">Deny</button>
{% endblock %}

EmpReview/templates/EmpReview/review_form.html
{% extends "base.html" %}

{% block content %}

    <form action="/review/create" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}

        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

EmpReview/templates/EmpReview/scratchtest.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        <li>
            {{ emps }}
        </li>
    </ul>
{% endblock %}